### Implement do while in python to find the even number 

In [ ]:
while True:
  try:
    num=int(input('Enter the number:'))
    print(num)
    if num%2==0:
       print('Even Number')
       break
    else:
      print('Not even number')
      break
  except:
    print('Error Occurred please try again')
    break

Enter the number:5
5
Not even number


### Sum of all the item in list

In [ ]:
## Using inbuilt function
from functools import reduce
l=list(map(int,input('Enter input:').split()))
reduce(lambda x,y:x+y,l)

Enter input:5 6 7


18

In [ ]:
def sum_list(list):
  sum=0
  for i in list:
    sum+=i
  return sum

## Drive code
# l=list(map(int,input('Enter input:').split()))
# result=sum_list(l)
# print(result)

result=sum_list([21,4,5,6])
print(result)


36


### Multiply all element of the list

In [ ]:
## Using Inbuit function
from functools import reduce
l=[1,2,3,4]
product=reduce(lambda x,y:x*y,l)
print(product)


24


In [ ]:
### Using User defind function

### Function declaration
def product_list(list):
  product=1
  for i in list:
    product*=i
  return product

### Drive code
l=[1,2,3,4]
product=product_list(l)
print('Product of given list is ',product)

Product of given list is  24


### Largest number from the list

In [ ]:
### Inbuilt function
l=[1,2,3,4,5]
print(f"largest elelemt in the list is {max(l)}")

largest elelemt in the list is 5


In [ ]:
def largest(input_list):
  input_list.sort()
  print(input_list)
  print('largest elelemt in given list is',input_list[-1])

## Drive code
largest([1,3,4,6,7,0])


[0, 1, 3, 4, 6, 7]
largest elelemt in given list is 7


In [ ]:
def largest_1(input_list):
  new_list=sorted(input_list)
  print(new_list)
  print('largest elelemt in given list is',new_list[-1])

## Drive code
largest_1([1,3,4,6,7,0,5,23])

[0, 1, 3, 4, 5, 6, 7, 23]
largest elelemt in given list is 23


In [ ]:
l=[1,3,5,7,9,0]
print(sorted(l)) ### Sort the element amn placed in  different memory location
print(l)

[0, 1, 3, 5, 7, 9]
[1, 3, 5, 7, 9, 0]


In [ ]:
### User defind function
'''
assign first element as max value and then compare each value from list to max value
if the condition is true then assign smaller value to max value variable and check again till the
loop is exhaust
'''
### Function declaration
def max_value(list):
  max_num=list[0]
  for num in range(len(list)):
    if max_num<list[num]:
      max_num=list[num]
    else:
      pass
  return max_num

### Driver code
l=[9,4,6,8,1,2]
largest_value=max_value(l)
print(f'Given list is:{l}')
print(f'largest element from the list is: {largest_value}')

Given list is:[9, 4, 6, 8, 1, 2]
largest element from the list is: 9


### Smallest value from the list

In [ ]:
## Inbuilt function
l=[2,5,8,9,0]
print(f"smallest element within the given list {l} is {sorted(l)[0]}")

smallest element within the given list [2, 5, 8, 9, 0] is 0


In [ ]:
l=[0,5,7,8,1,24,3]
print(f"smallest element within the given list {l} is {min(l)}")

smallest element within the given list [0, 5, 7, 8, 1, 24, 3] is 0


In [ ]:
## FUnction declaration
def smallest_element(list):
  return sorted(list)[0]

## Drive code
l=[-1,0,4,5,7,2,3]
result=smallest_element(l)
print(f"smallest element within the given list {l} is {result}")


smallest element within the given list [-1, 0, 4, 5, 7, 2, 3] is -1


In [ ]:
### User defind function
### Function declaration
def smallest_number(list):
  min=list[0]
  for num in range(len(list)):
    if min>list[num]:
      min=list[num]
    else:
      pass
  return min

### Drive code
l=list(map(int,input('Enter the list element').split()))
print(f"smallest number within given list is {smallest_number(l)}")

Enter the list element4 5 6 -0 0
smallest number within given list is 0


In [ ]:
-0==0 ## 0 is always treated as absolute number 

True

### String length is 2 or more and first and last character must be same

In [ ]:
def string_func(list):
  counter=0
  for ch in list:
    if len(ch)>=2 and ch[0]==ch[-1]:
      print(ch)
      counter+=1
  print(f'number of elelent which satisfied the condition is {counter}')

## Driver code
string_func(['asd','aaa','bb','zxz'])

aaa
bb
zxz
number of elelent which satisfied the condition is 3


In [ ]:
l=[]
print(len(l))

0


### Sorted in increasing order by the last element in each tuple from a given list of non-empty tuple

In [ ]:
l=[(1,2),(5,2),(9,0),(4,1)]
def sort_tuple(l):
  #return sorted(l) ###Sorted based on first element of tuple
  return sorted(l,key=lambda x:x[1]) ### Sorted based on first last elements of tuple

## Driver code
sort_tuple(l)

[(9, 0), (4, 1), (1, 2), (5, 2)]

### Remove duplicate elements from list 

In [ ]:
### User defind function
### Function declaration

def remove_duplicate(input_list):
  dup_list=[]
  for i in input_list:
    if i not in dup_list:
      dup_list.append(i)
    else:
      pass
  return dup_list

### Driver code
l=[1,1,1,13,3,3,3,4,4,4]
result=remove_duplicate(l)
print(f"final list after removal is {result}")


final list after removal is [1, 13, 3, 4]


In [ ]:
### Inbuilt function
### Function declaration 
def remove_duplicate(input_list):
  return list(set(input_list))

### Driver code
input_list=list(map(int,input("enter list element").split()))
result=remove_duplicate(input_list)
print(f"final list after removal is {result}")

enter list element2 4 54 3333 333 333 33 33 33 3
final list after removal is [33, 2, 3, 4, 3333, 333, 54]


In [ ]:
from collections import OrderedDict
list_val=[1,1,1,13,3,3,3,4,4,4]
list(OrderedDict.fromkeys(list_val))

#[1, 13, 3, 4]

In [ ]:
from collections import Counter
val=Counter(list_val) #return collection counter 
[*val] #return unique values

#[1, 13, 3, 4]

In [ ]:
import numpy as np
np.unique(list_val)

#[1, 13, 3, 4]

### To check whether a list is empty or not

In [ ]:
### Function declaration
def check_empty(l):
  if len(l)==0:
    print('Provided list is empty')
  else:
    print('Provide list is not empty')

### Driver code
check_empty([1,2,3,4])
check_empty([])


Provide list is not empty
Provided list is empty


In [ ]:
def check_empty_list(list):
  if l:
    print('Not empty')
  else:
    print('Empty')

l=[]
check_empty_list(l)

#Empty

In [ ]:
def check_empty_list2(list_2):
  if not list_2:
    return 'Empty List'
  else:
    return 'List is not empty'

l=[]
check_empty_list2(l)

#Empty List

In [ ]:
def check_empty_list3(list_3):
  if list_3==[]:
    return 'Empty List'
  else:
    return 'List is not empty'

l=[2,3,4,5]
check_empty_list3(l)

#List is not empty

In [ ]:
def check_empty_list4(list_4):
  if list_4.__len__() == 0:
    return 'Empty List'
  else:
    return 'List is not empty'

l=[2,3,4,5]
check_empty_list4(l)

#List is not empty

### List of words that are longer than n from given list of words

In [ ]:
def word_length_check(n,input_list):
  for i in range(len(input_list)):
    if len(input_list[i])>n:
      print(input_list[i])
    else:
      pass
  


In [ ]:
## Drive code
input_list=list(map(str,input('Enter the elelemtn within list:').split()))
word_length_check(2,input_list)

Enter the elelemtn within list:nitesh sarvesh pandey
nitesh
sarvesh
pandey


### compare 2 list and return True if atleast one common value present

In [ ]:
def list_compare(list1,list2):
  count=0
  for i in list1:
    if i in list2:
      count+=1
  if count>0:
    return True
  else:
    return False

### Driver code
list1=list(map(str,input('Enter elelemt in first list:').split()))
list2=list(map(str,input('Enter elelemt in Second list:').split()))
print(f"Common element present in list is {list_compare(list1,list2)}")
print(f"Common element present in list is {list_compare([1,2,'pandey'],['nitesh',8,9])}")

Enter elelemt in first list:344 555 55 234 nitesh
Enter elelemt in first list:nitesh 345
Common element present in list is True
Common element present in list is False


#### Write a program to find the value except specified the index position in argument

In [ ]:
def specific_elements(list,*element_index):
  l=[]
  for i in range(len(list)):
    if i not in element_index:
      l.append(list[i])
  return l

### Driver code
specific_elements([1,2,34,7,8],0,4,5)

[2, 34, 7]

### Shuffle and print the specified list

In [ ]:
#Shuffle function shuffle the element inplace
from random import shuffle,sample
ip_list=[2,3,4,5]
list_new=[5,6,7,8]
shuffle(ip_list)
sample(list_new,len(list_new))

[6, 7, 5, 8]

In [ ]:
print(ip_list) ## Changes in main list
print(list_new) ## create different reference variable without affecting the old list

[3, 2, 4, 5]
[5, 6, 7, 8]


### Flatten a shallow list

In [ ]:
list_value=[[1,2,3],[4,5,6],[7,8,9]]
def list_flatten(list_value):
  l=[]
  for i in list_value:
    l+=i
  return l

## Driver code
list_flatten(list_value)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

## Append the list

In [ ]:
l1=[1,3,5,7]
l2=[2,4,6,8]

In [ ]:
##l1.append(l2) ##[1, 3, 5, 7, [2, 4, 6, 8]]
##l1.insert(len(l2),l2) ##[1, 3, 5, 7, [2, 4, 6, 8]]
l1+l2 ##[1, 3, 5, 7, 2, 4, 6, 8]

[1, 3, 5, 7, 2, 4, 6, 8]

Select Item randomly from a list

In [ ]:
import random

## Function declaration
def random_sample(list):
  print(random.sample(list,1))

## Driver code
random_sample([1,4,6,'Nitesh'])
  

In [ ]:
### Function declaration
def random_sample(list1):
  return random.choice(list1)

### Driver code
random_sample([1,4,7,9])

In [ ]:
def second_largest(list):
  return sorted(list)[-2]

l=[4,6,8,8,0,2]
second_largest(l) ### It get failed in such a scenerio where duplicate value present in list

8

In [ ]:
### Funcion declaration
def second_largest(l):
  new_list=list(set(l))
  new_list.sort()
  print(new_list[-2])
  
##Driver code 
second_largest([4,6,8,8,0,2]) ### This logic work fine in all situation

### Unique values from list

In [ ]:
### Function declaration
def unique_values(list):
  new_list=[]
  for i in list:
    if i not in new_list:
      new_list.append(i)
  return new_list

## Driver code
unique_values([1,1,1,12,3,4,4,4,5])

[1, 12, 3, 4, 5]

In [ ]:
def unique_values(list1):
  #new_list=set(list1)
  #return list(new_list)
  return list(set(list1))

# Driver code
unique_values([1,2,3,4,5,4,3,2,1])

[1, 2, 3, 4, 5]

### Find frequency of element in a list

In [ ]:
#Method1---Inbuilt function
from collections import Counter
def values_frequency(l):
  return Counter(l)
  
## Driver code
values_frequency([1,2,3,2,1,3,4])

In [ ]:
#Method-2 --user defind function
def frequency_count(input_list):
  l=[]
  for i in set(input_list):
    l.append((i,input_list.count(i)))
  return l

## Driver code
frequency_count([1,1,1,2,2,2,3,4,5])

[(1, 3), (2, 3), (3, 1), (4, 1), (5, 1)]

In [ ]:
###Method-3 -- Function declaration (Using Dictionary)
def frquency_count(list_input):
  d={}
  count=0
  for i in set(list_input):
    if i in d:
      d[i]=count+1
    else:
      d[i]=i
  return d

### Driver code
frequency_count([1,2,3,2,22])

[(1, 1), (2, 2), (3, 1), (22, 1)]

### Check whether a list contain sublist or not

In [ ]:
l1=[1,2,3,'Nitesh']
l2=[[1,2,3],'Pandey','Nitsam']

def find_sublist(list1):
  for i in list1:
    if type(i)==list:
      return 'Nested list are present'
    else:
      return 'No nested list are present'

### Driver code
find_sublist(l1)  
#find_sublist(l2)

In [ ]:
from itertools import combinations
def sublist_find(input_list):
  l=[]
  for i in range(0,len(input_list)+1):
    temp=[list1 for list1 in combinations(input_list,i)]
    if len(temp)>0:
      l.extend(temp)
  return l

### Driver code
sublist_find(['Niteh','Pandey',1])


[(),
 ('Niteh',),
 ('Pandey',),
 (1,),
 ('Niteh', 'Pandey'),
 ('Niteh', 1),
 ('Pandey', 1),
 ('Niteh', 'Pandey', 1)]

### Convert list to dictionary

In [ ]:
names=['Nitesh','Sarvesh','Arun','Badal']
surnames=['Pandey','Pandey','Yadav','None']


In [ ]:
def list_to_dict(list1,list2):
  d={}
  count=0
  for name in names:
    d[name]=surnames[count]
    count+=1
  return d

### Driver code
list_to_dict(names,surnames)

{'Nitesh': 'Pandey', 'Sarvesh': 'Pandey', 'Arun': 'Yadav', 'Badal': 'None'}

### Sort list of nested dictionary 

In [ ]:
d=[{'Name':{'Surname':3}},{'Name':{'Surname':2}},{'Name':{'Surname':99}}]

def list_nested_dict_sort(inp_dic):
  inp_dic.sort(key=lambda x:x['Name']['Surname'])
  return inp_dic

list_nested_dict_sort(d)


[{'Name': {'Surname': 2}}, {'Name': {'Surname': 3}}, {'Name': {'Surname': 99}}]

### Find common elements from 2 list

In [ ]:
l1=['Nitesh','Badal']
l2=['Badal','Manish']
final_list=[]
for i in l1:
  if i in l2:
    final_list.append(i)
print(final_list)

['Badal']


In [ ]:
l=[1,2,3,4,5,6,7,8,0]
n=2

In [ ]:
import numpy as np
print(*np.array_split(l, 2))


[1 2 3 4 5] [6 7 8 0]


In [ ]:
def split(a, n):
    k, m = divmod(len(a), n)
    return (a[i*k+min(i, m):(i+1)*k+min(i+1, m)] for i in range(n))

In [ ]:
for i in split(l, 3):
  print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 0]


### Concate the value of list into single string

In [ ]:
l=[11,22,33]
m=[str(ele) for ele in l]
''.join(m)

In [ ]:
### Function Declaration
def list_to_string(input_list):
  string=""
  for i in input_list:
    string+=str(i)
  return string

### Driver code
list_to_string([11,22,33])

'112233'

In [ ]:
## Function declaration
def split_list_string(input_list):
  for i in input_list:
    print(i[0],i)

## Driver code
split_list_string(['Nitesh','Sarvesh','Pandey'])

N Nitesh
S Sarvesh
P Pandey


In [ ]:
l=[(5,3),(2,6),(3,5)]
def sorted_unique_value(list_new):
  return sorted(set().union(*l))

## Driver code
result=sorted_unique_value(l)
print(f'New list is {result}')

New list is [2, 3, 5, 6]


### Check if all elements in a list are identical

In [ ]:
def find_similar_list(list_new):
  if l.count(l[0])==len(l):
    return 'All element within list is same'
  else:
    return 'Element within list is not same'

l=[1,2,1,1]
find_similar_list(l)

'Element within list is not same'

In [ ]:
from itertools import groupby

def all_equal(iterable):
    g = groupby(iterable)
    print(list(g))
    return next(g, True) and not next(g, False)

In [ ]:
in_list=[['nitesh'],['pandey']]
for i in in_list:
  print(i)

['nitesh']
['pandey']


d={"title":['a','b','c'],"city":['x','y','z'],"likes":[1,2,3],"view":[10,20,30]}

**output-**
('a', 'x', 1, 10)
('b', 'y', 2, 20)
('c', 'z', 3, 30)

In [ ]:
### inbuit function
for i in zip(*d.values()):
  print(i)

('a', 'x', 1, 10)
('b', 'y', 2, 20)
('c', 'z', 3, 30)


In [ ]:
### Using pandas DF 
import pandas as pd
df=pd.DataFrame(d)
df.values.tolist()

[['a', 'x', 1, 10], ['b', 'y', 2, 20], ['c', 'z', 3, 30]]

In [ ]:
### Using custom function
def dict_print(dic):
  title,city,likes,view=list(dic.values())
  for i in zip(title,city,likes,view):
    print(i)
dict_print(d)

('a', 'x', 1, 10)
('b', 'y', 2, 20)
('c', 'z', 3, 30)


Smallest specified index position element from a list of tuple 

In [ ]:
l=[(4,5,6),(1,2,3),(0,4,6),(8,9,1)]
def find_element_tuple(list_input,position):
  return sorted(list_input,key=lambda x:x[position])[0][position]

find_element_tuple(l,1)

2

### Print space separated elements from list

In [ ]:
l=[1,2,3,4,5,6,7,8,9]
for ele in l:
  print(ele,end=' ')

1 2 3 4 5 6 7 8 9 

In [ ]:
print(*l)

1 2 3 4 5 6 7 8 9


### Move all zero digit to the end of a given list

In [ ]:
"""
first find occurance of 0 and then check the non zero number and at
the last append with the occurence of zeros 
"""
def append_zero_at_last(list_new):
  occurrence=x.count(0)
  list_new= [i for i in list_new if i != 0]
  list_new.extend([0]*occurrence)
  return list_new

### Driver code
x= [0,0,0,0,3,1,15,0,12,3,4,5]
append_zero_at_last(x)

[3, 1, 15, 12, 3, 4, 5, 0, 0, 0, 0, 0]

In [ ]:
"""
Create 2 different list one for non zero number and other for zero and 
at the last merge both the list to get the final result
"""
def append_zero_at_last(list_new):
  l=[]
  l_zero=[]
  for i in list_new:
    if i==0:
      l_zero.append(i)
    else:
      l.append(i)
  l.extend(l_zero)
  return l

### Driver code
x= [0,0,0,0,3,1,15,0,12,3,4,5]
append_zero_at_last(x)

[3, 1, 15, 12, 3, 4, 5, 0, 0, 0, 0, 0]

In [ ]:
def max_within_nested_list(list):
  return max(list,key=sum)
l=[[2,3,4],[4,5,6],[1,2,0],[7,6,8]]
result=max_within_nested_list(l)

[7, 6, 8]

In [ ]:
import numpy as np
def max_within_nested_list(list):
  list_sum=[]
  for i in range(len(l)):
    sum=0
    for j in range(len(l[1])):
      sum=sum+l[i][j]
    list_sum.append(sum)
  return max(list_sum),np.argmax(list_sum)
 
## Driver code
l=[[2,3,4],[4,5,6],[1,2,0],[7,6,8]]
result=max_within_nested_list(l)
print(f"sum of max value of nested list is {result[0]} and index position is {result[1]} and nested list is {l[result[1]]}")

sum of max value of nested list is 21 and index position is 3 and nested list is [7, 6, 8]


### Remove duplicate from nested list

In [ ]:
import itertools
l=[[10,20],[50],[10,20],[5]]

l.sort()
for x,_ in itertools.groupby(l):
  print(x)

[5]
[10, 20]
[50]


### Find the items start with specific character from a given list

In [ ]:
l=['aa','bb','abc']
def find_item(l,char):
  for i in l:
    if i.startswith(char):
      print(i)
   


In [ ]:
find_item(l,'a')

aa
abc


In [ ]:
import re
l=['aa','bb','abc']
def find_item(l,char):
  for i in l:
    if i[0]==char:
      print(i)
   

In [ ]:
find_item(l,'a')

aa
abc


### To check whether all dictionary in list is empty or not


In [ ]:
d1=[{},{},{}]
def find_empty_dict(in_dic):
  count=0
  for i in in_dic:
    if not i:
      count+=1
    if count==len(in_dic):
      return True



In [ ]:
result=find_empty_dict(d1)

In [ ]:
if result==True:
  print('Empty List')
else:
  print('Not empty list')

Empty List


In [ ]:
def empty_dict_within_list(d1):
  return all(not x for x in d1)

empty_dict_within_list(d1)

True

### Flatten nested list

In [ ]:
l_nested=[[0,10],[30,40]]

In [ ]:
def flatten(l):
  return [item for sublist in l for item in sublist]

l=flatten(l_nested)

### Create multidimensional list

In [ ]:
n_row=2
n_cols=3
l=[]
for i in range(n_row):
  l.append([])
  for j in range(n_cols):
    l[i].append(0)


In [ ]:
l

[[0, 0, 0], [0, 0, 0]]

In [ ]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
a=np.arange(9).reshape(3,3)

In [ ]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
!pip install python-string-utils

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import string_utils

In [ ]:
## Shuffle character within word
string_utils.shuffle('Nitesh')

'tseihN'

In [ ]:
l=['nitesh',2,4,'pandey']

In [ ]:
import numbers
for i in l:
  if isinstance(i,numbers.Number):
    print(i)
  

2
4


In [ ]:
for i in l:
  if type(i)==int:
    print(i)

2
4
