### **NumPy Basics**

NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.

* Numpy is developed on the top of numeric library.Numeric library developed by jim hugunin.
* Numpy is developed by travis oliphant and multiple contributors.
* Numy is freeware and open source library.
* Numpy is written in both python and C language.As most of numpy function is written in c ,performance wise numpy is good(spped is more)

Here are some of the things you’ll find in NumPy:
* ndarray an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* Mathematical functions for fast operations on entire arrays of data without having to write loops.
* Tools for reading/writing array data to disk and working with memory-mapped files.
* Linear algebra, random number generation, and Fourier transform capabilities.

* The array which are created by using numpy are called **nd arrays**.
This nd array in most commonly used in Data Science.

* An indexed collection of homogeneous data elements is nothing but array.

By default array concept is not available in python,instead we can use list(but make sure list and array both are not same)

But in python we can create array in the following 2 ways.
1. By using array module.
2. By using numpy module.

In [ ]:
##Need to specify the type of element
##Not recommended to use because much library is not support
import array
a=array.array('i',[10,20,30])
for i in a:
  print(i)

10
20
30


In [ ]:
import numpy as np
a=np.array([10,20,30])
print(a)

for i in a:
  print(i)

[10 20 30]
10
20
30


* 1D array know as Vector
* 2D array know as Metrix

In [ ]:
import numpy as np
import time

In [ ]:
start=time.time()
a=np.arange(100000000)
res=a**2
end=time.time()
print('Time Taken to execute the code',end-start)

Time Taken to execute the code 1.150693655014038


In [ ]:
start=time.time()
b=list(range(100000000))
res=[x**2 for x in b]
end=time.time()
print('Time Taken to execute the code',end-start)

Time Taken to execute the code 46.15275168418884


#### NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.

In [ ]:
#numpy array consume less memory to store the data sa compare to python list
import sys
a=np.array([10,20,30,40,50,60,70,80,90,10,20,30,40,50,60,70,80,90,10,20,30,40,50,60,70,80,90,10,20])
l=[10,20,30,40,50,60,70,80,90,10,20,30,40,50,60,70,80,90,10,20,30,40,50,60,70,80,90,10,20]
print('Size of array',sys.getsizeof(a))
print('Size of list', sys.getsizeof(l))

#Size of array 228
#Size of list 296


#### **Array Attributes**
#### There are various array attributes which mention as below
* ndim      --to get dimension of the array
* shape     --to get shape of the array
* size      --to get size of array which is nothing but the no of elements
* dtype     --to get data type of array elements
* itemsize  --the size of each array element in bytes

#### An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type. Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array:

#### Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array:


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)

(6,)
1
6
int64
8


In [ ]:
data=[1,2,3,45]
arr=np.array(data)

In [ ]:
data2=np.array([[1,2,3],[5,6,7]],dtype=float)

print(data2.size)
print(data2.itemsize)
print(data2.ndim)    
print(data2.shape)  
print(data2.dtype) 

6
8
2
(2, 3)
float64


#### **Numpy Data Types**
integer,float,string,complex,boolean    
i --->Integer(int8,int16,int32,int64)   
b --->boolean  
u --->unsigned integer  
f --->float  
c --->complex   
s --->string   
u --->unicode string   
M --->datetime   

#### Data Type 
Numpy Supported Data Type.

* int8, uint8           -Signed and unsigned 8-bit (1 byte) integer types.
* int16, uint16         -Signed and unsigned 16-bit integer types.
* int32, uint32         -Signed and unsigned 32-bit integer types.
* int64, uint64         -Signed and unsigned 64-bit integer types.
* float16               -Half-precision floating point.
* float32               -Standard single-precision floating point
* float64               -Standard double-precision floating point
* float128              -Extended-precision floating point
* complex64,complex128,complex256 -Complex numbers represented by two 32, 64, or 128 floats, respectivel

* bool                  -Boolean type storing True and False values
* object                -Python object type; a value can be any Python object




**Note-**   
A signed integer can represent both positive and negative integers, while an unsigned integer can only represent nonzero integers. For example, int8
(signed 8-bit integer) can represent integers from -128 to 127 (inclusive),while uint8 (unsigned 8-bit integer) can represent 0 through 255.

In [ ]:
import numpy as np
n=np.array([1,2,3,4,5,6,7,8])
print(sys.getsizeof(n),n.dtype) #default dtypes is int64 for integer values
n=np.array([1,2,3,4,5,6,7,8],dtype='int8')
print(sys.getsizeof(n))

n=np.array([1.2,3.4,5.6,7.,8.9])
print(sys.getsizeof(n),n.dtype)
n=np.array([1.2,3.4,5.6,7.,8.9],dtype='float32')
print(sys.getsizeof(n),n.dtype)


176 int64
120
152 float64
132 float32


In [ ]:
##Data Types
b=np.array([1,2,3,4],dtype=np.int64)
print(b)

[1 2 3 4]


In [ ]:
b=np.array([1,2,3,4],dtype=np.float64)
print(b)
print(b.dtype)

[1. 2. 3. 4.]
float64


In [ ]:
#you can use astype to convert the datatype (type casting)
b=np.array([1,2,3,4],dtype=np.int64)
print(b.astype(np.float64'))
c=np.float64(b)

dtype('float64')

In [ ]:
np.array(['a',1,2,4]).dtype

dtype('<U21')

Slicing and indexing  


    array[start:stop:steps] 
  
**Note-**
1. For begin,end and step,we can take both positive and negative values.
2. If step value is positive,then we have to consider element from begin to end-1 in forward direction(left to right).
3. If the step value is negative,then we have to consider elements from begin to end+1 direction(from right to left).
4. In forward direction if end value is zero then result is always empty.
5. In backward direction if end value is -1 then result is always empty.

In [ ]:
a=np.arange(10)

In [ ]:
print(a)
print(a[:4])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]


In [ ]:
a[:4]=10
print(a)

[10 10 10 10  4  5  6  7  8  9]


In [ ]:
a[1::2] #steps size of 2
a[::3]  #steps size of 3

array([0, 3, 6, 9])

In [ ]:
a[3:0] #refer point 4 for more clarification in above note section
a[-3:-1:-1] #refer point 5 for more clarification in above note section

array([], dtype=int64)

      arrayname[row,column] 
      row --begin:end:step   
      column --begin:end:step  

**Note-** Not able to fetch the element if they are not in order so for that we need to use advance indexing method


In [ ]:
# Accessing 2d array
arr2d=np.array([[10,20],[30,40],[50,60]])
#print(arr2d)
#print(arr2d.shape)
#print(arr2d[:,0:1])
#print(arr2d[1,:]) # print(arr2d[1:2,:])
#print(arr2d[:2,:])
#print(arr2d[::2,:])



[[10 20]
 [50 60]]


In [ ]:
ar=np.array(np.arange(16)).reshape(4,4)
print(ar)
print(ar.ndim)
print(ar.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2
(4, 4)


In [ ]:
ar[::3] # ar[::3,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [ ]:
ar[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [ ]:
ar[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

#### Slice on 3d array
sytax:

    a[i,j,k]
    i-->represent which 2-D arrays
    j-->represent which row in that 2-D arrays
    k-->represent which columns in that 2-D arrays

    a[begin:end:step,begin:end:step,begin:end:step]

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d.shape)
print('--'*10)
print(arr3d[0])
print(arr3d[0][0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
--------------------
[[1 2 3]
 [4 5 6]]
[1 2 3]


In [ ]:
arr3d=np.array(np.arange(1,25)).reshape(2,3,4)
print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
arr3d[:,:,:1]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [ ]:
arr3d[:,2,:] #or arr3d[:,2:3,:]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

#### If we want to access elements based on some condition then we can not use the basic indexing and slicing operators.For this requirement we should go for advance indexing.

syntax:

        array[x]  -->x can be either nd array or sequence like list or tuple,which represent required indexes.
      


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# access the value from index position 0,2,7
# Method-1
indexes=np.array([0,2,7])
print(a[indexes])

[1 3 8]


In [ ]:
# Method-2
a[[0,2,7]]

array([1, 3, 8])

In [ ]:
# We can access same element multiple time also
a[[0,2,7,2,2,2,0,0,0,7]]

array([1, 3, 8, 3, 3, 3, 1, 1, 1, 8])

In [ ]:
#Advance Indexing for 2d array
import numpy as np
a=np.array(np.arange(1,17)).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#a[[row_indexes],[column_indexes]]
a[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

In [ ]:
#Advance Indexing for 3d array
#array[[indexes of 2d array],[row indexes],[column indexes]]
arr3d=np.array(np.arange(1,25)).reshape(2,3,4)
print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# accessing value 1,14,24
arr3d[[0,1,1],[0,0,2],[0,1,3]]

array([ 1, 14, 24])

In [ ]:
# accessing value 6,16
arr3d[[0,1],[1,0],[1,3]]

array([ 6, 16])

In [ ]:
# accessing value of 16,10
arr3d[[-1,-2],[-3,-1],[-1,-3]]

array([16, 10])

#### Condition based indexes.
We can select array elements based on some condition also.  
**syntax**

    array[boolean_array]   -it select all elements where boolean array condition is true.

In [ ]:
import numpy as np
a=np.array([10,-5,20,40,-3,-1,75])
print(a)
print(a<0)
print('select all elements which are less than 0:',a[a<0])
print('select all elements which are greater than 10:',a[a>10])

[10 -5 20 40 -3 -1 75]
[False  True False False  True  True False]
select all elements which are less than 0: [-5 -3 -1]
select all elements which are greater than 10: [20 40 75]


In [ ]:
a=np.array(np.arange(1,25).reshape(2,3,4))
print(a)
print('value greater then 20',a[a>20])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
value greater then 20 [21 22 23 24]


#### In the case of advance indexing, a new copy will be created.If we perform any changes in one copy,those changes won't be reflected in other.

In [ ]:
a1=np.array([10,20,30,40,50,60,70])
print(a1)

[10 20 30 40 50 60 70]


In [ ]:
a2=a1[[0,2,5]]
print('id of array1',id(a1))
print('id of array 2',id(a2))
print(a2)

id of array1 139708977455248
id of array 2 139708977455632
[10 30 60]


In [ ]:
a1[0]=123
print('Value of array a1 is:',a1)
print('Value of array a2 is:',a2)

Value of array a1 is: [123  20  30  40  50  60  70]
Value of array a2 is: [10 30 60]


#### **Difference between slicing and advance indexing**

**1.**
* The element should be order and we can notselect arbitrary elements.
* The element should not be ordered and we can select arbitrary elements.

**2.**
* condition based selection is not posible.
* condition based selection is  posible.

**3.**
* In numpy slicing,we wont get a new object just we will get a view of the original object.If we perform any changes to original copy,those changes will be reflected to the sliced copy.
* But in the case of advanced indexing,a new copy will be created.If we perform any changes in one copy,then those changes won't be reflected in other.




### **Arithmetic Operation**

The following are various arithmetic operators :
1. +--->Addition
2. '-'--->Subtraction
3. *--->Multiplication
4. /--->Division
5. //--->Floor division
6. %---> modulo/remainder operation
7. '**'--->Exponetial operation/Power Operation

**Note**
All these python's arithmetic operators are applicable for numpy array also

Any arithmetic operations between equal-size arrays apply the operation element-wise:



In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[7., 8., 9.], [10., 11., 12.]])

In [ ]:
#Addition
print(a+a)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
#Addition of 2 array
print(arr1+arr2)

[[ 8. 10. 12.]
 [14. 16. 18.]]


In [ ]:
# Substraction of 2 array
print(arr1-arr2)

[[-6. -6. -6.]
 [-6. -6. -6.]]


In [ ]:
#Multiplication
print(a*10)

[[10 20 30]
 [40 50 60]]


In [ ]:
print(arr1*arr2)

[[ 7. 16. 27.]
 [40. 55. 72.]]


In [ ]:
#Multiplication of array
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
#Division
arr1/arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [ ]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
#Modulo Operation
arr1%2

array([[1., 0., 1.],
       [0., 1., 0.]])

In [ ]:
#Floor Operation
arr1//3

array([[0., 0., 1.],
       [1., 1., 2.]])

In [ ]:
#Power of 2
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In numpy we won't get zeroDivisionError.If the result is undefined(0/0) then it is treated as nan(not a number).If the result is infinity(10/0) then it is treated as inf

In [ ]:
print(1/0)

ZeroDivisionError: ignored

In [ ]:
from typing import no_type_check
import numpy as no_type_check
n=np.array([0,1,2,3])
1/n


<ipython-input-42-21be4d233426>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/n


array([       inf, 1.        , 0.5       , 0.33333333])

In [ ]:
n=np.arange(4)
print(n)
n/0

[0 1 2 3]


<ipython-input-45-0837ad3b3c7f>:3: RuntimeWarning: divide by zero encountered in true_divide
  n/0
<ipython-input-45-0837ad3b3c7f>:3: RuntimeWarning: invalid value encountered in true_divide
  n/0


array([nan, inf, inf, inf])

In [ ]:
#Produce an array of all 0s with the given shape and data type
print(np.zeros(10))
print(np.zeros((3,5)))

#This function is slightly different from numpy.ones(). Instead of taking a shape this function takes an array
print(np.zeros_like(np.array([1,2,3,4,2,7]).reshape(2,3)),int)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0]
 [0 0 0]] <class 'int'>


In [ ]:
#Create new arrays by allocating new memory, but do not populate with any values like ones and zeros
print(np.empty((3,4)))
print(np.empty_like(np.array([1,2,3,4,2,7]).reshape(2,3)))


[[1.98143407e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[[1 2 3]
 [4 2 7]]


In [ ]:
#Produce an array of all 1s with the given shape and data type
import numpy as np
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
#This function is slightly different from numpy.ones(). Instead of taking a shape this function takes an array
np.ones_like((np.array([1,2,3,4,2,7]).reshape(2,3)))

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)
import numpy as np
print(np.identity(4))
print(np.identity(2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
#Create a square N × N identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
#Be cautious when using the numpy.string_ type, as string data in NumPy is fixed size and may truncate input without warning. pandas has more intuitive out-of-the-box behavior on non-numeric data.
#Calling astype always creates a new array (a copy of the data), even if the new data type is the same as the old data type.



In [ ]:
import numpy as np
import time
import random

In [ ]:
# Comparision between array
arr1 ==arr2

array([[False, False, False],
       [False, False, False]])

In [ ]:
arr1>arr2

array([[False, False, False],
       [False, False, False]])

In [ ]:
arr1<arr2

array([[ True,  True,  True],
       [ True,  True,  True]])

For every arithmetic operator numpy library defines equivalent functino and we can use these functions also.

a+b  --->np.add(a,b)   
a-b  --->np.subtract(a,b)   
a*b  --->np.multiply(a,b)  
a/b  --->np.divide(a,b)  
a//b  --->                  
a%b  --->np.mod(a,b)   
a**b  --->np.power(a,b)   

#### Evaluating operations between differently sized arrays is called broadcasting

In [ ]:
import numpy as np
a=np.array(np.arange(1,5))
b=np.array(np.arange(6,10))
print(f'array a is {a}')
print(f'array b is {b}')

array a is [1 2 3 4]
array b is [6 7 8 9]


In [ ]:
print('Addition of array:',np.add(a,b))
print('Subtraction of array:',np.subtract(a,b))
print('Multiplication of array:',np.multiply(a,b))
print('Division of array:',np.divide(a,b))
print('Floor Division of array:',np.floor_divide(a,b))
print('Modulo of array:',np.mod(a,b))
print('Power of array:',np.power(a,b))

Addition of array: [ 7  9 11 13]
Subtraction of array: [-5 -5 -5 -5]
Multiplication of array: [ 6 14 24 36]
Division of array: [0.16666667 0.28571429 0.375      0.44444444]
Floor Division of array: [0 0 0 0]
Modulo of array: [1 2 3 4]
Power of array: [     1    128   6561 262144]


In [ ]:
import numpy as np
a=np.array(np.arange(1,5))
print(f'Actual array :{a}')
print(f'Array after addition(2 arguments): {np.add(a,a)}')
print(f'Final Array after passing(2 arguments):{a}')
print(f'Array after addition(3 arguments):{np.add(a,a,a)}') # Save the modification to original array because of 3rd argument(i.e out parameter)
print(f'Final Array after passing(3 arguments): {a}')
#print(f'Array after addition(4 arguments):{np.add(a,a,a,a)}') --max 3 positional arguments accept but 4 were given so that its shows error.

Actual array :[1 2 3 4]
Array after addition(2 arguments): [2 4 6 8]
Final Array after passing(2 arguments):[1 2 3 4]
Array after addition(3 arguments):[2 4 6 8]
Final Array after passing(3 arguments): [2 4 6 8]


In [ ]:
a=np.array([10])
print('1.',a)
print('2.',np.add(a,a))
print('value after addition',a)
np.add(a,a,out=a)
print('value after addition new',a)

1. [10]
2. [20]
value after addition [10]
value after addition new [20]


### **Broadcasting:**
1. Even though,array are of different dimension ,different shapes and different sizes,still we can perform arithmetic operation.It is possible by broadcasting.

2. Broadcasting wont be possible in all cases.it has some rules.If the rules are satisfied then only broadcasting will performed internally while performing arithmetic operation.

3. Broadcasting will be performed automatically and we are not required to perform explicitly.But being developer,we should aware when braodcasting will be performed and how it will be performed.

Note- If both arrays have same dimension,same shape and same size then broadcasting is not required.Different dimensions or different shapes or different sizes then only broadcasting is required.

**Note**
To perform arithmetic operators between numpy arrays,compulsory both arrays should have the same dimension,same shape and same size.otherwise we will get error.

* To handle this type of requirements we should go for broadcasting. 

**Rules for broadcasting**

1. If the 2 arrays of different dimensions,we should make equal dimensions.Padded 1s in the shape of fewer dimension array on the left side.
        array1 shape(4,3)
        array2 shape(3,) ----(1,3)


2. If the size of 2 arrays does not match in any dimension,the array with size equals to 1 in that dimension is expanded to match other size of the same dimension.
        array1 shape(4,3)
        array2 shape(1,3) ---->(4,3)   
      
Now both arrays are of same dimension and same shape,then arithmetic operation will be performed normally.

**Note** 
1. In any dimension,the sizes are not matched and neither equals to 1,then we will get error.

        example: 
        array1(4,3)
        array2(2,3)

2. Rule 2 fails and hence we will get ValueError and broadcasting won't be happend.

3. The result is always of higher dimension of input arrays.
        example:
        input array shape: 3-D,1-D
        ouput:3-D


In [ ]:
import numpy as np
a=np.array(np.arange(1,5))
b=np.array(np.arange(1,4))

In [ ]:
print(a.shape,b.shape) #Broadcasting is not possible because the sizes are not matched and neither equals to 1
print(a+b)

(4,) (3,)


ValueError: ignored

In [ ]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(f'shape of a is {a.shape} and shape of b is {b.shape}')
print(a+b)

shape of a is (3,) and shape of b is (3,)
[11 22 33]


In [ ]:
a=np.array([10,20,30])
b=np.array([50])
print(f'shape of a is {a.shape} and shape of b is {b.shape}') #internally broadcasting performed
print(a+b)

shape of a is (3,) and shape of b is (1,)
[60 70 80]


In [ ]:
#Broadcasting Performed in this case
a=np.array([[10,20],[30,40],[50,60]])
b=np.array([10,20])
print(f'shape of a is{a.shape} and shape of b is {b.shape}')
print(a+b)

shape of a is(3, 2) and shape of b is (2,)
[[20 40]
 [40 60]
 [60 80]]


In [ ]:
a=np.array([[10],[20],[30]])
b=np.array([30])
print(f'shape of a is{a.shape} and shape of b is {b.shape}')
print(f'shape of result is {(a+b).shape} and result is {a+b}')



shape of a is(3, 1) and shape of b is (1,)
shape of result is (3, 1) and result is [[40]
 [50]
 [60]]


#### **Array Manipulation**
**1. reshape()** --to change the array shape without affecting data.  
   **Note** -while using reshape() function,make sure the sizes should be matched otherwise we will get error.

        reshape(a,newshape,order='C')
        'C' -default value(c language style which means row major order)
        'F' -Fortran language style which means column major order.

        numpy.reshape(a,shape,order) #np.reshape(a,(5,2),order='C')
        ndarray.reshape(shape,order) #a.reshape((5,2),order='F')


In [ ]:
#To convert 1-D array to 2-D array
a=np.array(np.arange(1,11))
print(a.shape)
print('default order(C) which is row major order',a.reshape(5,2,order='C'))
print('Fortran language style which means column major order',a.reshape(5,2,order='F'))

(10,)
default order(C) which is row major order [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Fortran language style which means column major order [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


If we dont know the size of any dimension,we can use -1 so that numpy itself will evaluate the size

In [ ]:
  #numpy itself evaluate the size and perform action
a.reshape(5,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
a.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

reshape won't provide a separate new array object.it will provide just view of the existing arary because there is no change in data.Hence if we perform any change in the reshaped array,it will be reflected in the original array and vice-versa also.

In [ ]:
a=np.arange(1,16)
b=np.reshape(a,(5,3))
print(f'array b is {b}')
print(f'array a is {a}')

array b is [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
array a is [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
a[0][0]=45
print(a)

[[45  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


**2. resize()**

resize() function is used to create a new array with the specified shape. 

      numpy.resize(a,new_shape)
      return a new array with the specified shape





1. A separatenew array object will be created.
2. There may be a chance of changing data.
3. The size are need not be the same.
4. There is no chance to use -1 in the case of unknown dimension.

In [ ]:
import numpy as np
a=np.arange(1,6)

In [ ]:
#if the new array is larger then original array ,the new array is filled with repeated copies of 'a' 
np.resize(a,(2,4))

array([[1, 2, 3, 4],
       [5, 1, 2, 3]])

In [ ]:
c=np.resize(a,(2,2))
print(c)

[[1 2]
 [3 4]]


In [ ]:
#Note that this behaviour is different from a.resize(new_shape) which fills with zeros instead of repeated copies of 'a'
#if we are using ndarray class resize() method,inline modification will be happend.ie exisitng array only modified.
a=np.arange(1,5)
b=a.resize(4,2) 
print(a)
print(b)

[[1 2]
 [3 4]
 [0 0]
 [0 0]]
None


**reshape()** 
1. It is used to create a new array of the same size (as the original array) but of different desired dimensions.
2. The reshape will happend without changing original data.
3. In unknown dimension we can use -1.

**resize()** 
1. It can create an array of larger size than the original array.
2. There may be chance of data change in resize.
3.-1 such type of story is not applicable

**numpy.resize()**  
1. It will create a new array and return it.
2. If the new_shape requires more element then repeated copies of original array will be used.
3. It is a library function present in numpy module.

**ndarray.resize()**
1. It is a method present in ndarray class.
2. It wont return new array and existing array will be modified.
3. If the new_shape requires more element then extra element filled with zeros.


#### **Flatten**

1. Flatten returns a copy of single dimensional array by merging all sub-arrays.
2. This is a function of ndarray object.
3. We can use flatten() method to flatten(convert) any n-dimensional array to 1-dimensional array.

**Notes**

1. flatten will always create a new array object hence on the flatten copy,if we perform any changes then those changes wont be reflected on original copy.
2. flatten() will always returns 1-D array only.


**Note-**This function is not available for List of ndarrays object

     Syntax:
     ndarray.flatten(order='C')
     Parameter
      order(optional):'C','F','A','K'
      Default order is C
     'C' means to flatten in row-major(C-style) order.
     'F' means to flatten in column-major (Fortran-style) order.
     'A' means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise.
     'K' means to flatten a in the order the elements occur in memory.





In [ ]:
import numpy as np
a=np.arange(1,11).reshape(2,5)
print('Actual Array is',a)  
print('Flatten Array',a.flatten()) #row major order

Actual Array is [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Flatten Array [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a.flatten(order='F') #column major order

array([ 1,  6,  2,  7,  3,  8,  4,  9,  5, 10])

In [ ]:
#3d array to 1d array
b=np.arange(1,19).reshape(3,3,2)
print('Actual Array:',b)
print('Flatten Array:',b.flatten())
print('Flatten Array with order 'F':',b.flatten(order='F'))

Actual Array: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
Flatten Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Flatten Array with order : [ 1  7 13  3  9 15  5 11 17  2  8 14  4 10 16  6 12 18]


#### **flat**
1. This function is used to returns a 1-D iterator over the array.
2. This function behaves similar to Python’s built-in iterator.

        Syntax:
        numpy.ndarray.flat
        numpy.ndarray.flat[i]
            where i is index number
        


In [ ]:
a=np.arange(1,7).reshape(3,2)
print('Actual Array is',a)
print('Result of flat function is:',a.flat[4])

Actual Array is [[1 2]
 [3 4]
 [5 6]]
Result of flat function is: 5


In [ ]:
a1=np.array([9,8,6,3,2,1,5,4,7])
print(a1)
a=a1.reshape(3,3,order='C') 
print('value of flat function is:',a.flat[5])

[9 8 6 3 2 1 5 4 7]
value of flat function is: 1


#### **ravel()**

* We can use ravel() to flatten any n-dimensional array to 1-D array but it will return view but not a separate copy. 
* ravel is a library level function i.e numpy.
* This function returns a contiguous flattened array.
* Return array will have the same type as the input array.

        syntax:
        numpy.ravel(arr,order='C')

        Parameters
        arr-input array
        order-optional-{'C','F','A','K'}
        Default order is C 
        'C' means to flatten in row-major(C-style) order. 
        'F' means to flatten in column-major (Fortran-style) order. 
        'A' means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise.
        'K' means to flatten a in the order the elements occur in memory.


**Note**
For numpy library ravel()function,ndarray contain equivalent ravel()
method is available.We use anythings function will be same


In [ ]:
 import numpy as np
 a=np.arange(1,16).reshape(3,5)
 b=a.ravel()
 print('Array a is',a)
 print('Array b is',b)

Array a is [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array b is [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
b[0]=23
print(f'Array b after update {b}')
print(f'Array a after update of b {a}')

Array b after update [23  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Array a after update of b [[23  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
a=np.arange(8).reshape(2,4)
print('Array',a)
print('Array after ravel :',a.ravel())

Array [[0 1 2 3]
 [4 5 6 7]]
Array after ravel : [0 1 2 3 4 5 6 7]


#### **ravel() vs flatten()**

1. 
* It can be used to flatten 1-D array and a separate 1-D array object will be created.
* It can be used to flatten 1-D array but it won't be create a new 1-D array object and we will get only view.

2. 
* If we perform any changs in the flatten() copy,then those changes won't be reflected in the original copy.
* If we perform any changes in the ravel() copy,then those changes will be reflected in the original copy.

3.  
* flatten() method operats slower then ravel() as it is required to create a new array object.
* ravel() function operats faster then flatten() as it won't required to create a new array object.

4. 
* flatten() is not a numpy library level function and it is a method present in ndarray.
      eg:
      ndarray.flatten()---valid
      numpy.flatten(arr) --invalid

* ravel() is both numpy library level function and ndarray class method.
      eg:
      ndarray.ravel()--valid
      numpy.ravel(arr)--valid



#### **transpose or ndarray.T**

1. transpose() function permutes the dimension of the given array.
2. transpose() returns a view wherever possible.
1. ndarray.T is similar to numpy.transpose

        Syntax:
              transpose(arr, axes=None)
              Parameters:
                        arr: Input array.
                        axes: By default, reverse the dimensions, otherwise permute the axes according to the values given.



In [ ]:
d=np.array([[1,5,3],[2,5,6]])
print(f'Actual Array {d}')
print(f'Array after transpose {np.transpose(d)}')

Actual Array [[1 5 3]
 [2 5 6]]
Array after transpose [[1 2]
 [5 5]
 [3 6]]


In [ ]:
x = np.array([[1,2],[3,4]])
print(f'Actual Array {x}')
print(f'Array after transpose',x.T)

Actual Array [[1 2]
 [3 4]]
Array after transpose [[1 3]
 [2 4]]


In [ ]:
a=np.arange(12).reshape(3,4)

In [ ]:
print(a)
print('-'*20)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


* Use np.newaxis (or None) to add new axes. (Thus, increasing the dimension of the array)
* Use np.swapaxes to swap any two axes.
* Use np.transpose to permute all the axes at once.
* Use np.rollaxis to "rotate" the axes.

#### **swapaxes**
* By using transpose we can interchange any number of dimensions.but if we want to interchange only two dimensions then we should go for swapaxes() function.It is the specail case of transpose() function.

* This function interchanges the two axes of an array.

        numpy.swapaxes(arr, axis1, axis2)
        ndarray.swapaxes(axis1,axis2)
        Parameters:
                  arr: Input array whose axes are to be swapped
                  axis1: An int corresponding to the first axis
                  axis2:  An int corresponding to the second axis

**Note-**
ndarray class also contains swapaxes() method which is exactly same as numpy library swapaxes() function.

In [ ]:
import numpy as np
a=np.arange(1,7).reshape(3,2)
b=a.swapaxes(0,1)
print('Actual Array:',a)
print('shape of actual array',a.shape)
print('')
print('*'*40)
print('')
print('Array after swap',b)
print('shape of swap array',b.shape)

Actual Array: [[1 2]
 [3 4]
 [5 6]]
shape of actual array (3, 2)

****************************************

Array after swap [[1 3 5]
 [2 4 6]]
shape of swap array (2, 3)


**Note-**
There is no difference between these line just interchange rows and columns.

      np.swapaxes(a,0,1)
      np.swapaxes(a,1,0)
    

In [ ]:
a.swapaxes(1,0)

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
'''
0--1st axis
1--2nd axis
3--3rd axis
'''
n=np.arange(1,25).reshape(2,3,4)
print(f'shape of array before swap is {n.shape}')
print(f'array is {n}','\n')
print('*'*40,'\n')
s=np.swapaxes(n,0,2)
print(f'shape of array after swap is {s.shape}')
print(f'array is {s}')

shape of array before swap is (2, 3, 4)
array is [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 

**************************************** 

shape of array after swap is (4, 3, 2)
array is [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]


In [ ]:
s=np.swapaxes(n,1,2)
print(f'shape of actual array is {n.shape}')
print(f'shape of array after swap is {s.shape}')
print(f'array is {s}')

shape of actual array is (2, 3, 4)
shape of array after swap is (2, 4, 3)
array is [[[ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]
  [ 4  8 12]]

 [[13 17 21]
  [14 18 22]
  [15 19 23]
  [16 20 24]]]


#### **Difference between transpose() and swapaxes()**

* By using transpose() we can interchange any number of dimension
* By using swapaxes() we can change only two dimensions.

#### **Concatenate**
* Joining or concatinating of array by using concatenate() function.
* Concatenation refers to joining. This function is used to join two or more arrays of the same shape along a specified axis i.e row(axis=0) or column(axis=1) wise. Let us seen the syntax and some example of numpy concatenate operation.

**Rules**

* We can join any number of arrays,but all arrays should be of the same dimension
* The sizes of all axes except concatenation axis should be the same.
* The shaps of resultant array and out array must be the same.

        syntax:
        numpy.concatenate((a1,a2,a3,..,an),axis=0,out=None,dtype=None,casting="same_kind")

        a1, a2, ... : a sequence of array_like
          The arrays must have the same shape, except in the dimension corresponding to the axis (the first, by default).

        axis: int, optional
          The axis along which the arrays will be joined. The default is 0.

        out: ndarray, optional
          If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.


In [ ]:
import numpy as np
a=np.array(np.arange(8).reshape(2,4))
b=np.array(np.arange(8,16).reshape(2,4))

In [ ]:
np.concatenate((a,b)) # np.concatenate((a,b),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [ ]:
#concatenate of 2 1-D array
a=np.arange(4)
b=np.arange(5)

np.concatenate((a,b))

array([0, 1, 2, 3, 0, 1, 2, 3, 4])

In [ ]:
#concatenate of 3 1-D arrays
c=np.arange(6,10)
np.concatenate((a,b,c))

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 6, 7, 8, 9])

**Note**
1. The default data type for zeros() is float and hence the element are of float type.

2. Compulsory the out parameter shape and resultant array shape must be matched,otherwise we will get error.


In [ ]:
#storing result by using out parameter:
d=np.zeros(13,dtype='int32')
np.concatenate((a,b,c),out=d) 

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 6, 7, 8, 9], dtype=int32)

In [ ]:
import numpy as np 
d=np.zeros(10,dtype='int32')
np.concatenate((a,b,c),out=d) 

ValueError: ignored

In [ ]:
## Joining of two 2-D array
a=np.array(np.arange(1,9).reshape(2,4))
b=np.array(np.arange(1,13).reshape(3,4))
print(f'shae of array a is {a.shape}')
print(f'shae of array b is {b.shape}')

shae of array a is (2, 4)
shae of array b is (3, 4)


In [ ]:
## Row wise concatenation is possible
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
## column wise concatenation is not possible
np.concatenate((a,b),axis=1)

ValueError: ignored

In [ ]:
a=np.array(np.arange(1,9).reshape(4,2))
b=np.array(np.arange(1,13).reshape(4,3))
print(f'shae of array a is {a.shape}')
print(f'shae of array b is {b.shape}')

shae of array a is (4, 2)
shae of array b is (4, 3)


In [ ]:
#for above array we can perform only column wise operation not row wise
print(np.concatenate((a,b),axis=1))
print(np.concatenate((a,b),axis=0)) ## value error occurred

[[ 1  2  1  2  3]
 [ 3  4  4  5  6]
 [ 5  6  7  8  9]
 [ 7  8 10 11 12]]


ValueError: ignored

In [ ]:
## Joing of 3-D array
## We can concatenate but we should use axis 2
import numpy as np
a1=np.arange(1,13).reshape(2,3,2)
a2=np.arange(1,19).reshape(2,3,3)
print(np.concatenate((a1,a2),axis=2).shape)

(2, 3, 5)


In [ ]:
# Error Occurred
a1=np.arange(1,13).reshape(2,2,3)
a2=np.arange(1,17).reshape(2,2,4)
print(np.concatenate((a1,a2),axis=1).shape)

ValueError: ignored

In [ ]:
## axis=None is possible
print(np.concatenate((a1,a2),axis=None).shape)
print(np.concatenate((a1,a2),axis=None))

(28,)
[ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12
 13 14 15 16]


#### **Retrieve elements of nd array**

* By using basic indexing.
* By using slice operator.
* By using advanced indexing.
* Condition based selelction.


#### **we can iterate elelmets of nd array by using the following ways**

* By using python's loop 
* By using numpy nditer() function
* By using numpy ndenumerate() function


**1. By using python loop**

* if we iterate 2-D array by using python's for loop,we will get 1-D array

In [ ]:
# iterate element of 1-D array
a=np.array([10,20,30,40,50])
for i in a:
  print(i)



10
20
30
40
50


In [ ]:
# to iterate elelemts of 2-D array
a=np.array([[10,20],[30,40],[50,60]])

In [ ]:
print('print element one by one')
for x in a:
  for j in x:
    print(j)

print element one by one
10
20
30
40
50
60


In [ ]:
# to iterate elelemts of 3-D array
a=np.arange(1,13).reshape(2,3,2)

print('Print element of 3-D array one by one')
for i in a: #2-D array
  for j in i: #1-D array
    for k in j: #scaler value
      print(k)

**Note**
To iterate element of n-D array by using python ,we required n loop ,which is not convenient  to overcome this problem we should go for **nditer()** function

**2. By using numpy nditer() function**

**nditer()** 
* This function is specially designed function to iterate elements of any n-D array easily without multiple loops.

* beofre changing the data type we required temporary storage ,which is nothing but buffer.We have to enable that buffer other wise weget error

In [ ]:
#By using numpy nditer() function
#to iterate the element of 2-D array

a=np.array([[10,20],[30,40],[50,60]])
for i in np.nditer(a):
  print(i)


10
20
30
40
50
60


In [ ]:
# to iterate elelemts of 3-D array
a=np.arange(1,13).reshape(2,3,2)
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#change the data type of element using op_dtypes
a=np.arange(1,13).reshape(2,3,2)
for i in np.nditer(a,flags=['buffered'],op_dtypes=['float']):
  print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0


In [ ]:
# Slicing can also be used using nditer() function
a=np.arange(8).reshape(2,4)
print(a)
for i in np.nditer(a[:,:2]):
  print(i)


[[0 1 2 3]
 [4 5 6 7]]
0
1
4
5


#### **Normal python's for loop vs nditer()**

* To iterate n-d array ,n for loops are required.
* To iterate n-d array only one loop is required
---
* There is no way to specify our required type
* There is a way to specify our required type (op_dtypes argument)


**3. By Using numpy ndenumerate() function**

* By using nditer() function we will get elements only but not indexes.
* If we want index also in addition to element,then we should use ndenumerate() function.
* nuenumerate() function returns multidimensional index iterator which yield pairs of array coordinates and values.

In [ ]:
## To iterate elelemts of 1-D array
a=np.arange(5)
for key,value in np.ndenumerate(a):
  print(f'{value} present at index {key}')

0 present at index (0,)
1 present at index (1,)
2 present at index (2,)
3 present at index (3,)
4 present at index (4,)


In [ ]:
# To iterate elelemts of 2-D array
a=np.array([[10,20],[30,40],[50,60]])
for key,value in np.ndenumerate(a):
  print(f'{value} present at index {key}')

10 present at index (0, 0)
20 present at index (0, 1)
30 present at index (1, 0)
40 present at index (1, 1)
50 present at index (2, 0)
60 present at index (2, 1)


stack

* Join a sequence of arrays along a new axis.
* The axis parameter specifies the index of the new axis in the dimensions of the result. 
* For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.

      stack(arrays, axis=0, out=None)
        arrays-Sequence of arrays of the same shape
        axis-Axis in the resultant array along which the input arrays are stacked

      axis=0 --stack all input array row-wise
      axis=1 --stack all input array column-wise

**concatenate:**  The input array must have same shape.   
**stack:** The resultant stacked array has one more dimension than the input arrays.

In [ ]:
# for stacking of 1-D arrays
import numpy as np
a=np.array([10,20,30,40])
b=np.array([1,2,3,4,5])

In [ ]:
#all input array must have the same shape otherwise we will get the error msg.
np.stack((a,b))

ValueError: ignored

In [ ]:
#if we use 1-D array for stack then we get 2-D array as output.

a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(f'stacked array is {np.stack((a,b))} and shape is of {np.stack((a,b)).shape}')

stacked array is [[10 20 30 40]
 [ 1  2  3  4]] and shape is of (2, 4)


In [ ]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(f'stacked array is {np.stack((a,b),axis=1)} and shape is of {np.stack((a,b)).shape}')

stacked array is [[10  1]
 [20  2]
 [30  3]
 [40  4]] and shape is of (2, 4)


If we astack 2-D arrays the result will be 3-D array
3-D array shape:

      (x,y,z)
          x-->axis-0  --> The number of 2-D array.
          y-->axis-1  --> The number of rows in 2-D array.
          z-->axis-2  --> The number of columns in 2-D array.

In [ ]:
# array itself one by one 
a=np.array([[10,20],[30,40],[50,60]])
b=np.array([[30,50],[30,10],[70,90]])
print(f'shape of array of a is {a.shape} and shape of array b is {b.shape}')
print(f'stacked array is {np.stack((a,b))} and shape is of {np.stack((a,b)).shape}')

shape of array of a is (3, 2) and shape of array b is (3, 2)
stacked array is [[[10 20]
  [30 40]
  [50 60]]

 [[30 50]
  [30 10]
  [70 90]]] and shape is of (2, 3, 2)


In [ ]:
#stcking based on axis=1(row wise)
a=np.array([[10,20],[30,40],[50,60]])
b=np.array([[30,50],[30,10],[70,90]])
print(f'shape of array of a is {a.shape} and shape of array b is {b.shape}')
print(f'stacked array is {np.stack((a,b),axis=1)} and shape is of {np.stack((a,b)).shape}')

shape of array of a is (3, 2) and shape of array b is (3, 2)
stacked array is [[[10 20]
  [30 50]]

 [[30 40]
  [30 10]]

 [[50 60]
  [70 90]]] and shape is of (2, 3, 2)


In [ ]:
# Stacking based on axis=2(column wise)
a=np.array([[10,20],[30,40],[50,60]])
b=np.array([[30,50],[30,10],[70,90]])
print(f'shape of array of a is {a.shape} and shape of array b is {b.shape}')
print(f'stacked array is {np.stack((a,b),axis=2)} and shape is of {np.stack((a,b)).shape}')

shape of array of a is (3, 2) and shape of array b is (3, 2)
stacked array is [[[10 30]
  [20 50]]

 [[30 30]
  [40 10]]

 [[50 70]
  [60 90]]] and shape is of (2, 3, 2)


#### **hstack**
* Stack arrays in sequence horizontally (column wise).
* This is equivalent to concatenation along the second axis, except for 1-D arrays where it concatenates along the first axis. Rebuilds arrays divided by hsplit.

In [ ]:
x=np.array([[1,2],[3,4],[5,6]])         #(3,2)
y=np.array([[7,8],[9,10],[11,12]])      #(3,2)

z=np.hstack((x,y))
print('shape of the array',z.shape)
print(z)


shape of the array (3, 4)
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


**vstack**

* Stack arrays in sequence vertically (row wise).
* This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N). Rebuilds arrays divided by vsplit.

In [ ]:
a=np.array([1,2,3])
print(f'shape of array a is',a.shape)
b=np.array([5,6])
print(f'shape of array a is',b.shape)
c=np.vstack((a,b))#ValueError: all the input array dimensions except for the concatenation axis must match exactly

shape of array a is (3,)
shape of array a is (2,)


ValueError: ignored

In [ ]:
b=np.array([5,6,7])
print(f'shape of array a is',b.shape)
c=np.vstack((a,b)) 
print('shape of the array',c.shape)
print('final array after stacking is',c)

shape of array a is (3,)
shape of the array (2, 3)
final array after stacking is [[1 2 3]
 [5 6 7]]


#### **numpy.squeeze() function**

* The numpy.squeeze() function is used to remove single-dimensional entries from the shape of an array. It returns an array with the same data but reshaped dimensions.

* This function can be used to reduce the dimensions of an array, which is useful for data preprocessing in machine learning applications.

      Syntax:
      numpy.squeeze(a, axis=None)
          a -->	Input data.
          axis -->	Selects a subset of the single-dimensional entries in the shape. If an axis is selected with shape entry greater than one, an error is raised.

In [ ]:
import numpy as np
a=np.array([[[10],[20],[30]]])
print(f'shape of array a is:{a.shape}')
print(f'shape of array after squeeze is:{np.squeeze(a).shape}')

shape of array a is:(1, 3, 1)
shape of array after squeeze is:(3,)


In [ ]:
#Removes the dimension of size 1 at index 0 and returns a new array with shape (3, 1).
import numpy as np
a=np.array([[[10],[20],[30]]])
print(f'shape of array a is:{a.shape}')
print(f'shape of array after squeeze is:{np.squeeze(a,axis=0).shape}')

shape of array a is:(1, 3, 1)
shape of array after squeeze is:(3, 1)


In [ ]:
#Removes the dimension of size 1 at index 2 and returns a new array with shape (1, 3).
import numpy as np
a=np.array([[[10],[20],[30]]])
print(f'shape of array a is:{a.shape}')
print(f'shape of array after squeeze is:{np.squeeze(a,axis=2).shape}')

shape of array a is:(1, 3, 1)
shape of array after squeeze is:(1, 3)


In [ ]:
#It raises a ValueError as the axis=1 has size not equal to one and cannot be removed.
import numpy as np
a=np.array([[[10],[20],[30]]])
print(f'shape of array a is:{a.shape}')
print(f'shape of array after squeeze is:{np.squeeze(a,axis=1).shape}')

shape of array a is:(1, 3, 1)


ValueError: ignored

In [ ]:
# By default removes the dimension of size 1 at any index position if we does not defind the axis value.
b=np.arange(9).reshape(3,1,3)
print(f'array shape is {b.shape}')
print(f'array shape after squeeze is {np.squeeze(b).shape}')

array shape is (3, 1, 3)
array shape after squeeze is (3, 3)


In [ ]:
#Removes the dimension of size 1 at index 1 and returns a new array with shape (3, 3).
b=np.arange(9).reshape(3,1,3)
print(f'array shape is {b.shape}')
print(f'array shape after squeeze is {np.squeeze(b,axis=1).shape}')

array shape is (3, 1, 3)
array shape after squeeze is (3, 3)


#### **expand_dims**
* Expand the shape of an array.
* Insert a new axis that will appear at the axis position in the expanded array shape.
* This can be useful when we want to perform operations or calculations that require a specific shape or dimensionality of arrays.

        expand_dims(a, axis)
                a: Input array.
                axis: Position in the expanded axes where the new axis is placed.

In [ ]:
# required positional argument means we must be used axis to  expand dimensions
x = np.array([1,2])
print(f'shape of x array is {x.shape} and dimension is {x.ndim}')
print(f'shape of the x array after expands {np.expand_dims(x).shape}')

shape of x array is (2,) and dimension is 1


TypeError: ignored

In [ ]:
x = np.array([1,2])
print(f'shape of x array is {x.shape} and dimension is {x.ndim}')
print(f'shape of the x array after expands {np.expand_dims(x,axis=0).shape}')

shape of x array is (2,) and dimension is 1
shape of the x array after expands (1, 2)


In [ ]:
x = np.array([1,2])
print(f'shape of x array is {x.shape} and dimension is {x.ndim}')
print(f'shape of the x array after expands {np.expand_dims(x,axis=1).shape}')

shape of x array is (2,) and dimension is 1
shape of the x array after expands (2, 1)


In [ ]:
x = np.array(np.arange(8).reshape(2,4))
np.expand_dims(x,axis=1)

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]])

In [ ]:
x = np.array(np.arange(8).reshape(2,4))
np.expand_dims(x,axis=0)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

#### **Pseudorandom Number Generation**

* The **numpy.random** module supplements the built-in Python random module with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions. 

* Python’s built-in random module, by contrast, samples only one value at a time. As you can see from this benchmark, numpy.random is well over an order of magnitude faster for generating very large samples.

        from numpy import random
        random.standard_normal()



In [ ]:
#standard normal distribution using numpy.random module
from numpy import random
random.standard_normal((3,3)) # random.standard_normal(size=(3,3))

array([[-0.85414637, -1.54378116,  1.79579688],
       [-1.29332115,  1.62772548, -0.76987804],
       [-1.5567852 , -0.5267291 , -0.1154339 ]])

In [ ]:
# Generate one value at a time if we won't provide the size
random.standard_normal() 

0.3106190164576942

**permutation** : Return a random permutation of a sequence, or return a permuted range.

**shuffle** : Randomly permute a sequence in place   
**uniform** : Draw samples from a uniform distribution   
**binomial**: Draw samples from a binomial distribution  
**normal**  : Draw samples from a normal (Gaussian) distribution  
**beta**    : Draw samples from a beta distribution  
**chisquare**: Draw samples from a chi-square distribution  
**gamma**   : Draw samples from a gamma distribution  

In [ ]:
#permutation*
random.permutation(4)

array([2, 3, 0, 1])

In [ ]:
#shuffle
arr=[1,2,3,45]
random.shuffle(arr)
print(arr)

[1, 45, 2, 3]


In [ ]:
#Draw samples from a uniform distribution
#random.uniform()

random.uniform()

0.0705593249177473

In [ ]:
#random.binomial(n, p, size=None)
#Draw samples from a binomial distribution.

n,p = 10,.5
s = random.binomial(n, p, 10)
print(s)

[5 6 4 6 2 4 5 3 5 5]


In [ ]:
#Draw samples from a normal (Gaussian) distribution
#random.normal(loc=0.0, scale=1.0, size=None)

print(random.normal(0.2,1))

mu, sigma = 0, 0.1 # mean and standard deviation
s =random.normal(mu, sigma, 10)
print(s)

-1.0709041986915886
[-0.07346597  0.05143514 -0.01577955  0.13242487 -0.18407918  0.15469435
  0.19940792 -0.07395421 -0.06078584 -0.03283129]


In [ ]:
#random.beta(a, b, size=None)
#Draw samples from a Beta distribution.
random.beta(1,2)

0.15408240687070865

In [ ]:
#Draw samples from a chi-square distribution
#random.chisquare(df, size=None)

random.chisquare(2,4)

array([2.32083032, 2.38835486, 7.41136664, 1.03702647])

In [ ]:
#random.gamma(shape, scale=1.0, size=None)
#Draw samples from a Gamma distribution.

shape, scale = 2., 2.  # mean=4, std=2*sqrt(2)
s =random.gamma(shape, scale, 10)
print(s)

[ 5.99299993  3.0619051   2.36147874  8.35196624 12.68495107  3.31031574
  3.03538072  3.49164355  3.12845374  4.93020418]


**Universal Functions: Fast Element-Wise Array Functions**

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. 


In [ ]:
import numpy as np
arr=np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
arr=np.arange(10)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr)

9

In [ ]:
#numpy.maximum computed the element-wise maximum of the elements in x and y.

x=np.arange(1,5)
y=np.arange(4,8)
print(x)
print(y)

[1 2 3 4]
[4 5 6 7]


In [ ]:
np.maximum(x,y)

array([4, 5, 6, 7])

In [ ]:
x=np.array([1,4,7,0])
y=np.array([2,3,4,5])
np.maximum(x,y)

array([2, 4, 7, 5])

####**Expressing Conditional Logic as Array Operations**

In [2]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [3]:
# we wanted to take a value from xarr whenever the corresponding value in cond is True, and otherwise take the value from yarr
np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
#check the value greater than 1 in xarray .if condition is matched then return True.
xarr>1

array([ True,  True,  True,  True,  True])

In [7]:
#return value 1 whenever condition is satisfied else return 0
np.where(xarr>1.2,1,0)

array([0, 0, 1, 1, 1])

#### Mathematical and Statistical Methods
A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of the array class.

In [21]:
arr=np.random.standard_normal((2,3))
print(arr)

[[-1.27620958  1.84552713 -1.44796767]
 [ 2.56171784 -0.22691084  0.25465201]]


In [22]:
#Arithmetic mean; invalid (returns NaN) on zero-length arrays
#Functions like mean and sum take an optional axis argument that computes the
#statistic over the given axis, resulting in an array with one less dimension:
print(arr.mean())
print(np.mean(arr))

0.28513481427731824
0.28513481427731824


In [28]:
#Here, arr.mean(axis=1) means “compute mean across the columns,” where
#arr.sum(axis=0) means “compute sum down the rows.”


In [26]:
np.mean(arr,axis=1)

array([-0.29288337,  0.863153  ])

In [27]:
#Sum of all the elements in the array or along an axis; zero-length arrays have sum 0
arr.sum(axis=0)

array([ 1.28550825,  1.61861629, -1.19331566])

In [23]:
print(np.median(arr))

0.013870582539158044


In [24]:
np.min(arr)

-1.4479676668210788

In [29]:
#Cumulative sum of elements starting from 0
a1=np.array([1,2,3,4,5,6])
np.cumsum(a1)

array([ 1,  3,  6, 10, 15, 21])

In [30]:
# Cumulative product of elements starting from 1
a1=np.array([1,2,3,4,5,6])
np.cumprod(a1)

array([  1,   2,   6,  24, 120, 720])

#### Methods for Boolean Arrays


In [31]:
print(arr)

[[-1.27620958  1.84552713 -1.44796767]
 [ 2.56171784 -0.22691084  0.25465201]]


In [33]:
# Number of positive values
(arr>0).sum()

3

In [34]:
# Number of non positive values
(arr<=0).sum()

3

#### Two additional methods, any and all, are useful especially for Boolean arrays. any tests whether one or more values in an array is True, while all checks if every value is True

In [45]:
bools = np.array([False, False, True, False])

In [46]:
bools.any()

True

In [47]:
bools.all()

False

In [48]:
# arr.sort(axis=0) sorts the values within each column, while arr.sort(axis=1) sorts across each row:
arr.sort()
print(arr)

[[-0.68808041 -0.30851447  0.38533715]
 [ 0.26831922  0.29415497  2.21525619]]


In [55]:
arr=np.random.standard_normal((2,3))
print('array before sorting',arr)
print('*'*40)
arr.sort(axis=0)
print('array after sorting',arr)

array before sorting [[-1.30930957  0.91042847  1.20951074]
 [-0.33702223 -1.14309671 -0.16204614]]
****************************************
array after sorting [[-1.30930957 -1.14309671 -0.16204614]
 [-0.33702223  0.91042847  1.20951074]]


In [53]:
arr=np.random.standard_normal((2,3))
print('array before sorting',arr)
print('*'*40)
arr.sort(axis=1)
print('array after sorting',arr)

array before sorting [[-0.83008268 -0.42229766 -0.02377552]
 [ 0.00745107  0.96866308 -1.25732223]]
****************************************
array after sorting [[-0.83008268 -0.42229766 -0.02377552]
 [-1.25732223  0.00745107  0.96866308]]


#### NumPy has some basic set operations for one-dimensional ndarrays.

In [56]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
print(np.unique(names))

['Bob' 'Joe' 'Will']


In [57]:
#Compute the sorted, unique elements in b
b=np.array([[1,1],[1,1],[2,3],[3,4]])
np.unique(b)

array([1, 2, 3, 4])

In [61]:
#Compute the sorted, common elements in a1 and a2
a1=np.array([1,2,3,4,5])
a2=np.array([7,8,9,1])
np.intersect1d(a1,a2)

array([1])

In [63]:
#Compute the sorted union of elements
np.union1d(a1,a2)

array([1, 2, 3, 4, 5, 7, 8, 9])

In [58]:
# numpy.in1d, tests membership of the values in one array in another, returning a Boolean array:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])



array([ True, False, False,  True,  True, False,  True])

In [65]:
#Compute a Boolean array indicating whether each element of x is contained in y
np.setdiff1d(a1,a2)

array([2, 3, 4, 5])

In [66]:
#Set symmetric differences; elements that are in either of the arrays, but not both
np.setxor1d(a1,a2)

array([2, 3, 4, 5, 7, 8, 9])

#### File Input and Output with Arrays
* NumPy is able to save and load data to and from disk in some text or binary formats.

* NumPy is able to save and load data to and from disk in some text or binary formats.

* You can save multiple arrays in an uncompressed archive using numpy.savez and passing the arrays as keyword arguments:

In [67]:
arr=np.arange(10)
np.save('demo_file',arr)

In [69]:
np.load('demo_file.npy')


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.savez("array_archive.npz", a=arr, b=arr)

In [71]:
#When loading an .npz file, you get back a dictionary-like object that loads the individual arrays lazily:
val=np.load('array_archive.npz')
val['b']


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
val['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Linear algebra operations, like matrix multiplication, decompositions, determinants, and other square matrix math, are an important part of many array libraries.

In [77]:
a=np.array(np.arange(1,10).reshape(3,3))
b=np.array(np.arange(10,19).reshape(3,3))

print(f'array a is {a}')
print('\n')
print(f'array a is {b}')

array a is [[1 2 3]
 [4 5 6]
 [7 8 9]]


array a is [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [78]:
#Matrix multiplication
np.dot(a,b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [81]:
a.dot(b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [82]:
#Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, 
#or convert a 1D array into a square matrix with zeros on the off-diagona
np.diag(a)

array([1, 5, 9])

In [83]:
#Compute the sum of the diagonal elements
np.trace(a)

15

In [88]:
#Compute the determinant of an array.
from numpy import linalg
linalg.det(a)

0.0

In [90]:
#Compute the eigenvalues and eigenvectors of a square matrix
linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [96]:
# Compute the inverse of a square matrix
from numpy.linalg import inv
new_arr=np.array([[1., 7.], [4., 2.]])
inv(new_arr)

array([[-0.07692308,  0.26923077],
       [ 0.15384615, -0.03846154]])