### np.sort()

Return a sorted copy of an array

In [ ]:
import random
import numpy as np

a=np.random.randint(1,100,15)
print(a)

[ 9 92 57 92 82 88 73 15 95 64 53 13 24 49 95]


In [ ]:
b=np.random.randint(1,100,24).reshape(6,4)
print(b)

[[24 43 67 78]
 [68 82 19 35]
 [ 8 27 21 87]
 [91 69 24 17]
 [96 49 88 68]
 [84 98 16 48]]


In [ ]:
np.sort(a)

array([ 9, 13, 15, 24, 49, 53, 57, 64, 73, 82, 88, 92, 92, 95, 95])

In [ ]:
np.sort(b,axis=0)

array([[ 8, 27, 16, 17],
       [24, 43, 19, 35],
       [68, 49, 21, 48],
       [84, 69, 24, 68],
       [91, 82, 67, 78],
       [96, 98, 88, 87]])

In [ ]:
np.sort(b)## defult row level sorting done

array([[24, 43, 67, 78],
       [19, 35, 68, 82],
       [ 8, 21, 27, 87],
       [17, 24, 69, 91],
       [49, 68, 88, 96],
       [16, 48, 84, 98]])

###np.append()
the numpy.append() appends values along the mentioned axis at the end of the array

In [ ]:
np.append(a,[1,2])

array([ 9, 92, 57, 92, 82, 88, 73, 15, 95, 64, 53, 13, 24, 49, 95,  1,  2])

In [ ]:
np.append(b,np.ones((b.shape[0])).reshape(6,1),axis=1)

array([[24., 43., 67., 78.,  1.],
       [68., 82., 19., 35.,  1.],
       [ 8., 27., 21., 87.,  1.],
       [91., 69., 24., 17.,  1.],
       [96., 49., 88., 68.,  1.],
       [84., 98., 16., 48.,  1.]])

###np.concatenate()
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [ ]:
l=np.arange(6).reshape(2,3)
m=np.arange(6,12).reshape(2,3)

print(l)
print(m)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((l,m)) ##Default row level concatenation performed

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((l,m),axis=1) ##columns level concatenation performed

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

###np.unique()

with the help of np.unique() method,we can get the unique values from an array given as parameter in np.unique() method

In [ ]:
s=np.array([1,2,2,2,2,2,2,2,2,3,3,3,3])
np.unique(s)

array([1, 2, 3])

###np.expand_dims()
with the help of expand_dims method,we can get expanded dimensions of an array

In [ ]:
a

array([ 9, 92, 57, 92, 82, 88, 73, 15, 95, 64, 53, 13, 24, 49, 95])

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1).shape

(15, 1)

###np.where()
this function returns the indices of elements in an input array where the given condition is satisfied

In [ ]:
np.where(a>50)

(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 14]),)

In [ ]:
#np.where(condition,true,false)
np.where(a>70,0,a)

array([ 9,  0, 57,  0,  0,  0,  0, 15,  0, 64, 53, 13, 24, 49,  0])

In [ ]:
np.where(a%2==0,0,a)

array([ 9,  0, 57,  0,  0,  0, 73, 15, 95,  0, 53, 13,  0, 49, 95])

###np.argmax
The numpy.argmax() function return indices of the max element of the array in a particular axis. 

In [ ]:
a

array([ 9, 92, 57, 92, 82, 88, 73, 15, 95, 64, 53, 13, 24, 49, 95])

In [ ]:
np.argmax(a)

8

In [ ]:
np.argmax(b)

21

In [ ]:
np.argmax(b,axis=1)

array([3, 1, 3, 0, 0, 1])

###np.argmin()

In [ ]:
np.argmin(a)

0

###np.cumsum()
this function is used when we want to compute the cumulative um of array elements over a given axis

In [ ]:
a

array([ 9, 92, 57, 92, 82, 88, 73, 15, 95, 64, 53, 13, 24, 49, 95])

In [ ]:
np.cumsum(a)

array([  9, 101, 158, 250, 332, 420, 493, 508, 603, 667, 720, 733, 757,
       806, 901])

In [ ]:
b

array([[24, 43, 67, 78],
       [68, 82, 19, 35],
       [ 8, 27, 21, 87],
       [91, 69, 24, 17],
       [96, 49, 88, 68],
       [84, 98, 16, 48]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 24,  67, 134, 212],
       [ 68, 150, 169, 204],
       [  8,  35,  56, 143],
       [ 91, 160, 184, 201],
       [ 96, 145, 233, 301],
       [ 84, 182, 198, 246]])

###np.cumprod()

In [ ]:
np.cumprod(a)

array([                   9,                  828,                47196,
                    4342032,            356046624,          31332102912,
              2287243512576,       34308652688640,     3259322005420800,
         208596608346931200, -7391123831322198016, -3850889438640816128,
        -187626158831828992, -9193681782759620608, -6402797897815031808])

###np.percentile()
This function is used to compute the nth percentile of the given data(array elements)along the specified axis

In [ ]:
np.percentile(a,50)

64.0

In [ ]:
np.percentile(a,100)

95.0

###np.histogram()
Numpy has a built in functionwhich represent the frequency of data distribution in the graphical form.

In [ ]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([3, 1, 3, 2, 6]), array([  0,  20,  40,  60,  80, 100]))

###np.corrcoef
Return Pearson product-moment correlation coefficients

In [ ]:
height=np.array([3,4,5,6,7])
weight=np.array([30,35,48,60,65])

In [ ]:
np.corrcoef(height,weight)

array([[1.       , 0.9876562],
       [0.9876562, 1.       ]])

###np.isin()
with the help of this method we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [ ]:
a

array([ 9, 92, 57, 92, 82, 88, 73, 15, 95, 64, 53, 13, 24, 49, 95])

In [ ]:
item=np.array([9,57])

In [ ]:
np.isin(a,item)

array([ True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

###np.flip()
this function reverses the order of array elementsusing the specified axis,preserving the shape of the array

In [ ]:
print(a)
np.flip(a)

[ 9 92 57 92 82 88 73 15 95 64 53 13 24 49 95]


array([95, 49, 24, 13, 53, 64, 95, 15, 73, 88, 82, 92, 57, 92,  9])

In [ ]:
print(b)
np.flip(b) ## row and column level flipping internally

[[24 43 67 78]
 [68 82 19 35]
 [ 8 27 21 87]
 [91 69 24 17]
 [96 49 88 68]
 [84 98 16 48]]


array([[48, 16, 98, 84],
       [68, 88, 49, 96],
       [17, 24, 69, 91],
       [87, 21, 27,  8],
       [35, 19, 82, 68],
       [78, 67, 43, 24]])

In [ ]:
print(b)
np.flip(b,axis=0) ## column level fliping

[[24 43 67 78]
 [68 82 19 35]
 [ 8 27 21 87]
 [91 69 24 17]
 [96 49 88 68]
 [84 98 16 48]]


array([[84, 98, 16, 48],
       [96, 49, 88, 68],
       [91, 69, 24, 17],
       [ 8, 27, 21, 87],
       [68, 82, 19, 35],
       [24, 43, 67, 78]])

In [ ]:
print(b)
np.flip(b,axis=1) ### row level fliping

[[24 43 67 78]
 [68 82 19 35]
 [ 8 27 21 87]
 [91 69 24 17]
 [96 49 88 68]
 [84 98 16 48]]


array([[78, 67, 43, 24],
       [35, 19, 82, 68],
       [87, 21, 27,  8],
       [17, 24, 69, 91],
       [68, 88, 49, 96],
       [48, 16, 98, 84]])